### ISSUE TITLE
Download of satellite data: shift not defined

### ISSUE THREAD

**Issue by characat0** [natgeo-wong/NASAPrecipitation.jl#4]
While trying to download Final IMERG Half Hourly data for the Global IMERG Dataset I encountered the following error:
```ERROR: UndefVarError: shift not defined
Stacktrace:
 [1] download(npd::NASAPrecipitation.IMERGHalfHourly{String, Date}, geo::RectRegion{String, Float64})
   @ NASAPrecipitation ~/Documents/VSCode/JuliaClimate/dev/NASAPrecipitation/src/downloads.jl:44
 [2] download(npd::NASAPrecipitation.IMERGHalfHourly{String, Date})
   @ NASAPrecipitation ~/Documents/VSCode/JuliaClimate/dev/NASAPrecipitation/src/downloads.jl:19
 [3] top-level scope
   @ REPL[20]:1
```
Seems like the problem is in [downloads.jl](https://github.com/natgeo-wong/NASAPrecipitation.jl/blob/main/src/downloads.jl#L44), it also looks like the same problem is replicated along all definitions of download.

**Comment by natgeo-wong** [comment]
Hey thank you so much!  There was a bug in the code.  I have fixed it, please try the latest version.

Also I apologize for the slow response.  Have been away for the past few days.

Issue should now be closed pending further bugs.
